### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by kpointer11** [pmorerio/video-gesture-autism#4]
Hi, I'm a researcher in Korea and really interested in ur project.
But, I can't download the dataset. 
If u can't upload the dataset on the online, could you send me them by e-mail?
My mail is kpointer11@yonsei.ac.kr 
I hope some good news buddy. 
Thx :)

**Comment by zeBaus** [comment]
Hi I am a graduating student of the University of San Carlos and I am in need of datasets for our thesis in regards to early detection of children with disabilities. I am unable to download the dataset and if it would be possible may I request for the dataset via email ?
My email is jrmsuan2000@gmail.com

Thank you!

**Comment by abdelrhman2023** [comment]
Hi I am a student of the University of Ain Shams and I am in need of datasets for our thesis in regards to early detection of children with disabilities. I am unable to download the dataset and if it would be possible may I request for the dataset via email ?
My email is [abdelrhmansayed01@gmail.com](mailto:abdelrhmansayed01@gmail.com)

**Comment by DylanFantast** [comment]
Hi, I'm a graduating student of the Beihang University and I'm interested in ur dataset for my graduation design concerning  classification of sequential image. I can download the dataset, could you please send the dataset to me by e-mail?
my e-mail is 2391970059@qq.com.

**Comment by vanshika462** [comment]
Hi, I'm an undergrad student of MNNIT Allahabad, India and I'm really interested in studying your project. Image Detection is something that interests me and I want to work on the dataset myself. Kindly send me the dataset if possible.
my e-mail is vanshika.20204223@mnnit.ac.in

**Comment by 249498576** [comment]
Hi, I'm a graduate student from the School of Computer and Information Technology, Hefei University of Technology, China. My research focuses on Diagnosis of Autism, and I believe that your dataset would be extremely valuable for my work. could you please send the dataset to me by e-mail?
my e-mail is [2023170701@mail.hfut.edu.cn](mailto:2023170701@mail.hfut.edu.cn).
